recipe: default.v1

assistant_id: 20240110-074001-foggy-compressor

# # RegexFeaturizer 
# Tạo các tính năng để trích xuất thực thể và phân loại mục đích. một tính năng sẽ được đặt để đánh dấu xem biểu thức này có được tìm thấy trong tin nhắn của người dùng hay không. Tất cả các tính năng sau đó sẽ được đưa vào trình phân loại/trình trích xuất thực thể nhằm đơn giản hóa việc phân loại

#LexicalSyntacticFeaturizer Tạo các đặc điểm từ vựng và cú pháp cho thông báo của người dùng để hỗ trợ trích xuất thực thể.
language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer  
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_chatgpt_fallback"
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true





# # backup
# # The config recipe.
# # https://rasa.com/docs/rasa/model-configuration/
# recipe: default.v1

# # The assistant project unique identifier
# # This default value must be replaced with a unique assistant name within your deployment
# assistant_id: 20240110-074001-foggy-compressor

# # Configuration for Rasa NLU.
# # https://rasa.com/docs/rasa/nlu/components/
# language: vi
# pipeline:
# # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # # If you'd like to customize it, uncomment and adjust the pipeline.
# # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# # Configuration for Rasa Core.
# # https://rasa.com/docs/rasa/core/policies/
# # policies: null
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
# #   - name: MemoizationPolicy
# #   - name: RulePolicy
# #   - name: UnexpecTEDIntentPolicy
# #     max_history: 5
# #     epochs: 100
# #   - name: TEDPolicy
# #     max_history: 5
# #     epochs: 100
# #     constrain_similarities: true
# policies:
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true

# # chat gpt
#   - name: FallbackPolicy
#     nlu_threshold: 0.4
#     core_threshold: 0.3
#     fallback_action_name: "action_chatgpt_fallback"
